### PR TITLE
Add Brexit and US Election 2016 logos

### PR DESCRIPTION
**Pull request by sumeetadur**

### CODE REVIEW

**Comment by sumeetadur** [comment]
@AlbertoElias could you peer review this? Is it ok to have PNGs in this repo?

**Comment by AlbertoElias** [comment]
They do need to be SVGs, yes

**Comment by sumeetadur** [comment]
@AlbertoElias I've replaced the PNG with an SVG. Good to go?

**Comment by AlbertoElias** [comment]
Thanks!

**Pull request merged**
